apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-vault
  template:
    metadata:
      labels:
        app: config-server-vault
    spec:
      serviceAccountName: internal-app
      containers:
        - name: config-server-vault
          image: gnanbu/config-server-vault:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  internal-app
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: internal-app
    namespace: default